services:
  - type: web
    name: pricehunter
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python app.py